# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: darksea 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hublot.hull
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - darksea

  adminer:
    image: adminer
    restart: always
    ports:
      - 1312:8080
    networks:
      - darksea

  ms_community:
    image: darkseacollective/ms_account:version1.0
    ports:
      - "8081:8081"
    networks:
      - darksea
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: darksea
      DB_PASSWORD: root
      DB_NAME: hublot.hull
    depends_on:
      - db
    

  ms_account:
    image: darkseacollective/ms_account:version1.0
    ports:
      - "8082:8082"
    networks:
      - darksea
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: darksea
      DB_PASSWORD: root
      DB_NAME: hublot.hull
    depends_on:
      - db

  ms_post:
    image: darkseacollective/ms_post:version1.0
    ports:
      - "8083:8083"
    networks:
      - darksea
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: darksea
      DB_PASSWORD: root
      DB_NAME: hublot.hull
    depends_on:
      - db

networks:
  darksea:
    driver: bridge