# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: darksea 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hublot.hull
    expose:
      - "5430"
      - "5432"
    ports:
      - "5430:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: collective@darksea.com
      PGADMIN_DEFAULT_PASSWORD: hublot.admin
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  adminer:
    image: adminer
    restart: always
    ports:
      - 1312:8080